### ISSUE TITLE
Whether I can use "readMultiVars" method like "readArea" method in multi DBs of S7-300 PLC

### ISSUE THREAD

**Issue by wangxqdev** [comtel2000/mokka7#1]
I'm now using "readArea" method to read DBs of S7-300, but I found the number of DB (12 vars per DB) is too much, so the efficient is too lower. And now I found "readMultiVars" method, whether I can use "readMultiVars" method to read multi DBs once communication to increase the efficient? Thank you and waiting for your response.

**Comment by comtel2000** [comment]
Here you can find samples for multivar reading:
mokka7/mokka7-samples/src/main/java/org/comtel2000/mokka7/ReadMultiVarsSample.java

**Comment by comtel2000** [comment]
MultiVar reading and writing reduce the payload and should be more efficient for multiple random adress areas. Just try it..
