### ISSUE TITLE
writeBit and writeByte writes always 0 !

### ISSUE THREAD

**Issue by a3dh4m3d** [comtel2000/mokka7#2]
hi i have one problem with writeBit() and writeByte() methods!
in writeBit method, you first set value in bitPos'th position of first byte(buffer[0]) and in continue write buffer in ((start * 8) + bitPos)  of area. this causes this method write always 0 for me! 
I changed the method as follows to work correctly:
  default boolean writeBit(AreaType area, int db, int start, int bitPos, boolean value) throws S7Exception {
        // reset first byte?
        // S7.setByteAt(buffer, 0, (byte) 0x00);
        // S7.setBitAt(buffer, 0, bitPos, value);
        S7.setBitAt(buffer, (start * 8) + bitPos, bitPos, value);
        return writeArea(area, db, (start * 8) + bitPos, 1, DataType.BIT, buffer);
    }
and similarly in writeByte method.

**Comment by lambdaupb** [comment]
There is a bug in the `writeInternalArea` method.

Here is a patch:
```

Index: mokka7-core/src/main/java/org/comtel2000/mokka7/S7Client.java
<+>UTF-8
===================================================================
--- mokka7-core/src/main/java/org/comtel2000/mokka7/S7Client.java	(revision 0a4b81d5035f7cd9353e2cf79f1a8c032ae944be)
+++ mokka7-core/src/main/java/org/comtel2000/mokka7/S7Client.java	(date 1600968684296)
@@ -938,7 +938,7 @@
             final byte[] buffer) throws S7Exception {
         int maxElements = (pduLength - 35) / wordSize; // 35 = Reply telegram header
         int totElements = amount;
-        int offset = start;
+        int offset = 0;
         int position = start;
         while (totElements > 0) {
             int numElements = totElements;
```

**Comment by a3dh4m3d** [comment]
yes, i wrote a override for writeInternalArea method And added offset to method inputs directly.

**Comment by comtel2000** [comment]
Thx, but why not provide a PR? I will check the patch

**Comment by lambdaupb** [comment]
Didn't have the time that day.

**Comment by lambdaupb** [comment]
The library is also reusing static buffers for packets without synchronization, this leads to corruption when multiple connections are used at the same time.

**Comment by comtel2000** [comment]
Your right, but different topic and working on the same memory area with multiple connections result in strange states anyway with or /wo sync.
The static byte array reflects the plc internal memory and will be used for read and write.
So multiple connections should not be used for the same mem. area at all.

**Comment by lambdaupb** [comment]
No, The Client class uses `final static byte[]` buffers for packets, I don't mean the PLC side.
